### ISSUE TITLE
Instead of 20 seconds can you change it to 15 seconds so it's faster

### ISSUE THREAD

**Issue by Kody1** [YieldingExploiter/KrnlKey#2]
:D

**Comment by YieldingExploiter** [comment]
@Kody1 Internally it sits at around 16-ish seconds.
The text document indicates higher to account for network latency increase post-timeout-start.
The internals are not at 15s to account for network latency decrease post-timeout-start.

tl;dr there's around a 1 second buffer incase your network speed changes internally, and there's a 2-3 second buffer in terms of what the text says

**Comment by Kody1** [comment]
Can u make it auto click and submit the recaptcha?

**Comment by YieldingExploiter** [comment]
> Can u make it auto click and submit the recaptcha?

captchas are, by design, made difficult to automate.
the code atm is ~100-ish lines long - adding captcha completion via integration via a paid captcha solving service like 2captcha would, not only cost me money, but increase the code size to ca. ~500-ish lines long *minimum*.
+ most, if not all services charge money since they have actual humans completing captchas; fully automatic captcha solvers require you to have millions to invest in the technology behind

**Comment by Kody1** [comment]
I meant since I have one click captcha make a feature where it automatically clicks and enable it to change what browser it uses

**Comment by Kody1** [comment]
Also may I suggest that you make the first Get krnl key and bypass linkvertise option instantly take u to the site instead of waiting first

**Comment by YieldingExploiter** [comment]
> Also may I suggest that you make the first Get krnl key and bypass linkvertise option instantly take u to the site instead of waiting first

It has to wait 15-20s otherwise the server will reject it, unless i use a weird exploit that isn't consistent at all
