### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by aydynx** [YieldingExploiter/KrnlKey#4]
first, you can easily get source from decompiling this with dnspy.
second, you could update this to use puppeteer sharp with the [noptcha](https://chrome.google.com/webstore/detail/noptcha-recaptcha-hcaptch/dknlfmjaanfblgfdfebhijalfmhmjjjo) extension.
lastly, it would be much easier to parse through the html to get the key and display it to console or whatever instead of the horrendous webview2 interface

ps, open source this...

**Comment by xLeDocteurx** [comment]
Yup open source this and I guess we would both be glad to help with @aydynx suggestions

**Comment by YieldingExploiter** [comment]
> first, you can easily get source from decompiling this with dnspy.

I'm fully aware, and honestly didn't care - see the end of this reply

> second, you could update this to use puppeteer sharp with the [noptcha](https://chrome.google.com/webstore/detail/noptcha-recaptcha-hcaptch/dknlfmjaanfblgfdfebhijalfmhmjjjo) extension.

Thanks for the suggestion - haven't heard of that extension lol

> lastly, it would be much easier to parse through the html to get the key and display it to console or whatever instead of the horrendous webview2 interface

The WV2 interface is literally just a forced-dark-theme-variant of the actual krnlkey, which likely broke due to icebear updating internal shit

> ps, open source this...

I would have originally done this, but didn't want some quickly thrown together code to be copy-pasted into too many similar repositories, and have it end up spreading too much - I'll likely rewrite this and open-source the rewrite

**Comment by YieldingExploiter** [comment]
> with the [noptcha](https://chrome.google.com/webstore/detail/noptcha-recaptcha-hcaptch/dknlfmjaanfblgfdfebhijalfmhmjjjo) extension

After a bit of testing, it seems very unreliable, sometimes taking >30s for a single captcha, causing puppeteer (js) to crash with `TimeoutError: Navigation timeout of 30000 ms exceeded`

**Comment by YieldingExploiter** [comment]
Closing all issues due to archival.
